version: '2.1'

services:
  service-center:
    image: "servicecomb/service-center"
    hostname: service-center
    ports:
      - "30100:30100"

  mysql:
    image: "mysql/mysql-server:5.7"
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=saga
      - MYSQL_USER=saga
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    healthcheck:
        test: ["CMD-SHELL", "nc -z localhost 3306 &> /dev/null; echo $$?"]
        interval: 30s
        timeout: 10s
        retries: 5

  car-rental-service:
    image: "car-rental-service:0.0.3-SNAPSHOT"
    hostname: car
    links:
      - "service-center:sc.servicecomb.io"
    ports:
      - "8080"

  flight-booking-service:
    image: "flight-booking-service:0.0.3-SNAPSHOT"
    hostname: flight
    links:
      - "service-center:sc.servicecomb.io"
    ports:
      - "8080"

  hotel-reservation-service:
    image: "hotel-reservation-service:0.0.3-SNAPSHOT"
    hostname: hotel
    links:
      - "service-center:sc.servicecomb.io"
    ports:
      - "8080"

  payment-service:
    image: "payment-service:0.0.3-SNAPSHOT"
    hostname: payment
    links:
      - "service-center:sc.servicecomb.io"
    ports:
      - "8080"

  saga:
    image: "saga-spring:0.0.3-SNAPSHOT"
    hostname: saga
    links:
      - "mysql:mysql.servicecomb.io"
      - "service-center:sc.servicecomb.io"
      - "car-rental-service:car.servicecomb.io"
      - "flight-booking-service:flight.servicecomb.io"
      - "hotel-reservation-service:hotel.servicecomb.io"
      - "payment-service:payment.servicecomb.io"
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=prd,servicecomb -Dcse.service.registry.address=http://sc.servicecomb.io:30100
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy

  web:
      image: "saga-web:0.0.3-SNAPSHOT"
      hostname: web
      links:
        - "service-center:sc.servicecomb.io"
        - "saga:saga.servicecomb.io"
      environment:
        - JAVA_OPTS=-Dspring.profiles.active=prd,servicecomb -Dcse.service.registry.address=http://sc.servicecomb.io:30100
      ports:
        - "8888:8888"