spring:
  profiles: prd
  datasource:
    username: saga
    password: password
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql.servicecomb.io:3306/saga?useSSL=false
    platform: mysql
    continue-on-error: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none

saga:
  thread:
    count: 32
  retry:
    delay: 3000
