sudo: required

language: java

jdk:
  - oraclejdk8

script:
  - mvn clean install -Pjacoco -Pdocker coveralls:report
  - mvn clean verify -f saga-demo -Pdemo -Pdocker -Ddocker.useColor=false -Ddocker.showLogs

after_success:
  - mvn deploy -DskipTests --settings .travis.settings.xml

env:
  global:
    - secure: "P1ttjXKvVPkjQNFm0KhjFds9egqA2vwxJUseRhyTSajZDuR10Y7SrQNVTCg6w0xq+Y3SepMQfdyoU3HkMD7PWfZ6csMwLi4GlSwoRrKLI37l036o27U1pinX7lh1sCoAQCk5a1do1lwaeOjIqUulNuqCKsHcYTLxh56crbIhrPkl2VX6oP8r+dKsjbIDtwtYB9ArZ8okbaukY1UbPUjV3085EE1yl+KCJ6yJLB0lEfejGY+T1fps27Z0b1jvpuGE+tIeOPQPepmZb8Ca0D0hCQ74H9/IiwTSc7PH7V7F9wI/YkmjGeP/1o8zrPZlUikWEkKnl02airbxK4aOX4RNws0PVGe0TTzl0kbo1xMjc/yFE2hsu43PK+gEQwKuM/qzA47nKVhkToEKW5A7s6MXM6K102tvrhz657g/DwCoJ6rQ53KbbW28eUi33rgUMu7WtFf+acGR2AtLxrUSHK1VjxBDlt3aZi+WCWv+80xLqbACXeVkFpUmWODaE7tZhp4xZMDkC2gYYWeg0ZhHWjJ0OwXbmYliKk0zbDN6Uv+9umnScO6KLmZZCKzN4OxGOTH87q9VHJZYU1hqI0SO+K6UHcOtxawvjBSrj7Qtg5V9ra/KIerGlSq+8BeYmgXSBsGmc1jm4le5+/DWUtzBLxN3xzVTbKQNuhc2mUnprQzyy9k="
    - secure: "XwqEXhXWhuGcPoxOqTyE0LIW0UgTL2rnGDYiDAx5WF8T/MUcuBFXIx0qQwB4d5+u/a9y6gC2YUuP3mII3wu3x6PDxa3lupLXj7KWiOb40A0LH1aOAhaE8nRtDF1duoepLoPQyK7mkJLAN1UCwiagXIwuqn/Zjj7t3WUOj6yFq5mjsquG9ZA9R6wXbTw4A+3LLtsb8ZahPui4SDRGwscwigfSmBBz8rqFDPw60DxHuDfx+QxvB6rxdD54Ml2JSPoTZAVPRBZa4LPsCBTJqUxSo3hpKsufRS8svl1ThERVsAClP9jm+98jIr8wzUY5htffkZyWnNkYLS5JsAVyG2pfn0oFyNZVjW2CBh+kAwiJoTXMQR6O7CTj3700Qo7tOMCsaBqBX53QevUyicLypbMYgrkPauHi44IL0Wza9AIQ2+qVumCftySy2fXR0U85D5VnxwyBLJurUGJJY9md6hQl17Ayhn2Ah5qpnGWtIF9/0AGAZmKeZ5LQYS7j/5fVKlQF6WkSbbFVqNmN3KMlq2Ng6rJ17XwrsgL291AinUbILkWvWw+r4Oh1g6SsSTGhbOTNgyytXjUk25zMDg2vYH5ImY66+Ym/UBjY/lygd/6j/drVxabgupbATpBl8TC3nOZbmjrujc177Y6Lu9SuWFplQy1LYufxZiEdXWzI0ydUAIk="
